### ISSUE TITLE
Add short description to readme explaining how this works

### ISSUE THREAD

**Issue by adrian-gierakowski** [MercuryTechnologies/nix-your-shell#33]
Hi, thanks for the useful tool. Would be create to know how this works thought, without having to read the code.

**Comment by 9999years** [comment]
Sure. How'd you come across this tool, btw? I never did a release announcement but there's clearly several users scattered around.

**Comment by 9999years** [comment]
Opened a PR for this (#34), let me know if it makes sense!

**Comment by 9999years** [comment]
I merged my PR and closed this but let me know if you think it needs more detail.
