### ISSUE TITLE
Detect the 'nix run' command

### ISSUE THREAD

**Issue by arthsmn** [MercuryTechnologies/nix-your-shell#52]
Using something like `nix run nix -- develop` isn't working, this is important because you can run different versions of nix with this command (`nix run nix/2.19.1 -- develop`).

**Comment by 9999years** [comment]
I think this is a broader scope than what I'm interested in supporting. I think it would be challenging to figure out which Flake expressions evaluate to the Nix binary. (This would involve parsing `nix registry list`, which doesn't yet have JSON output, for example...)

If you're constructing a command like `nix run nix -- develop`, you (probably?) are going to be using it in a test script for checking a particular Nix version's support. Perhaps `nix run nix -- develop --command fish` (for example) would be a reasonable workaround?
